/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Solo para mockup de asesor. En prod requeriría auth. */
        get: operations["listLeads"];
        put?: never;
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAppointments"];
        put?: never;
        post: operations["createAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AppointmentType: "test_drive" | "service";
        /** @enum {string} */
        Hotspot: "wheels" | "seats" | "screen" | "battery" | "trunk" | "lights";
        ModelSummary: {
            id: string;
            name: string;
            price: number;
            segment: string;
            rangeKm: number;
            thumbnail: string;
            has3d?: boolean;
        };
        Model: components["schemas"]["ModelSummary"] & {
            specs?: {
                [key: string]: unknown;
            };
            hotspots?: {
                id: components["schemas"]["Hotspot"];
                label: string;
                position: number[];
            }[];
        };
        LeadCreate: {
            name: string;
            phone: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            source: "web" | "whatsapp";
            interest?: string;
            recommendedModels?: string[];
            /** @constant */
            consent: true;
            sessionId?: string;
        };
        Lead: components["schemas"]["LeadCreate"] & {
            id: string;
            /** Format: date-time */
            createdAt: string;
            afterHours: boolean;
            /** @enum {string} */
            crmStatus?: "pending" | "pushed" | "failed";
        };
        Recommendation: {
            modelId: string;
            name: string;
            price: number;
            reason: string;
        };
        ChatRequest: {
            sessionId: string;
            message: string;
            modelId?: string;
        };
        ChatResponse: {
            reply: string;
            suggestedActions: ("recommend" | "leave_contact" | "book_test_drive" | "book_service" | "view_3d")[];
            hotspot?: components["schemas"]["Hotspot"];
        };
        Slot: {
            id: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location: string;
            available: boolean;
        };
        AppointmentCreate: {
            leadId: string;
            type: components["schemas"]["AppointmentType"];
            slotId: string;
            vehicle?: string;
            notes?: string;
        };
        Appointment: components["schemas"]["AppointmentCreate"] & {
            id: string;
            /** @enum {string} */
            status: "confirmed" | "cancelled";
            /** Format: date-time */
            createdAt: string;
            slot: components["schemas"]["Slot"];
            leadName?: string;
            leadPhoneMasked?: string;
        };
    };
    responses: {
        /** @description No encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Error de validación */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Demasiadas solicitudes */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo público */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSummary"][];
                };
            };
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"][];
                };
            };
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    profile: string;
                    sessionId?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Recommendation"][];
                    };
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    availability: {
        parameters: {
            query: {
                type: components["schemas"]["AppointmentType"];
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
        };
    };
    listAppointments: {
        parameters: {
            query?: {
                type?: components["schemas"]["AppointmentType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"][];
                };
            };
        };
    };
    createAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Slot ya ocupado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Validation"];
        };
    };
}
